### PR TITLE
Extend filter by all

### LINKED ISSUE #46: Extend `filterByAll()` API to support all columns
- [x] The parameter dictionary on the server side should be updated to support more filtering options.

We will need to talk about this on the Discord to figure out what exactly what needs to be sent. Coordinate with the assigned person on #68.

### PR DESCRIPTION
**Pull request by tgustafson2**
Fixes #46 
Let me know if the changes to apiTest and api are acceptable.  They were made so that in filterbyall the constraint array variables would not be undefined when filtering

### CODE REVIEW

**Review by raymondwzeng — APPROVED** [review]
Looks good to me. Though I'm not sure if we should let the user filter by ID since it's mainly just something to use internally?

**Comment by tgustafson2** [comment]
> Looks good to me. Though I'm not sure if we should let the user filter by ID since it's mainly just something to use internally?

I'm not sure on that. We could hard code the ID filters to max in functions done by the user, or maybe we let the user search by ID as well

**Comment by AaronGeesink** [comment]
I think that we should leave filtering by ID. That way, we can potentially add IDs to the data display on the client so that we can use the filters for it. leaving the ability to filter by ID doesn't cause any data access issues, and leaves us open to potential future feature development.

**Review by AaronGeesink — APPROVED** [review]

**Comment by AaronGeesink** [comment]
Let's hold of merging this into main for now. Merging this will cause filtering the break on the client. I want to make the API call work on the client side first. Then we are good to merge this into main.

**Comment by AaronGeesink** [comment]
I added sliders on the client for all 15 column in the database. As of right now, we can modify all 15 of the sliders to change what we filter. If we want to remove any filtering options later on, we can simply do so by deleting the react component for that slider so that it always stays at the default min and max.

**Review by AaronGeesink — APPROVED** [review]
The filtering works on the client end. I don't think it's a problem that we have distances from cities AND latitude/longitude at the same time. The sliders take up a lot of space on the client, but we can fix the size and position of sliders in future sprints.

**Review by dukeph0 — APPROVED** [review]
Looks alright for the most part

**Review by raymondwzeng — APPROVED** [review]

**Review by garrettgeesink — APPROVED** [review]
It works, but there are too many sliders. Also the sliders don't feel very reactive (they feel laggy). I would say we can fix it later but I don't even think we will. Merging.

**Pull request merged**
