### PR TITLE
Added column to csv and implemented ID in neighborhood class, modifie…

### LINKED ISSUE #37: Add ID variable to neighborhood class
Add a new data member to the neighborhood class for a unique ID. We have 2 choices to implement an ID. 
- Choice 1: The id is stored as a column in the CSV file and set when the data is loaded (This would be the better implementation of the 2 choices)
- Choice 2: The neighborhood constructor makes a unique id using the other neighborhood data.

### LINKED ISSUE #38: Modify csv.load() function to assign neighborhood IDs
extension of issue #37. Make any necessary modifications in the csv.load() function so that each neighborhood has a unique id when loaded. Ideally, Unique IDs should be persistent, meaning that the ID for a neighborhood should be the same even after modifications to the dataset are made.

### PR DESCRIPTION
**Pull request by tgustafson2**
…d app.js for displaying ID
Fixes #37 Fixes #38

### CODE REVIEW

**Comment by AaronGeesink** [comment]
If We get the greenlight from the TA saying we can create IDs like this, then i would like to merge using this branch instead of #32 . If for some reason the TA doesn't want us to add columns to our csv file, then we'll just have to merge #32 and check for duplicates whenever we CREATE or UPDATE.

**Review by AaronGeesink — APPROVED** [review]
The professor has given us the green light for this implementation. If everything is to your liking, go ahead and merge.

**Comment by AaronGeesink** [comment]
Just noticed that the id is undefined on the client. It's a simple fix, we just needed to change a single variable name on the client.

**Review by AaronGeesink — APPROVED** [review]

**Review by garrettgeesink — APPROVED** [review]
I fixed the id output so not it shows the id instead of undefined on the webpage.

**Pull request merged**
