### PR TITLE
Added client post request function

### LINKED ISSUE #4: Send POST request to server
A bit of a follow-up to #3, but that's fine. Task involves adding the functionality to the button, and do:
- [ ] Sends a POST request with the form's information to the server in question

### PR DESCRIPTION
**Pull request by tgustafson2**
Fixes #4

### CODE REVIEW

**Review by raymondwzeng — APPROVED** [review]
Looks good to me!

**Comment by raymondwzeng** [comment]
@dukeph0 Make sure to take a look at this PR (and merge/branch off of it!) to resolve #5

**Review by AaronGeesink — APPROVED** [review]
Looks good to me. Let's create an issue to make unit tests for the client POST request so that we can verify that it works without having to run the server.

**Comment by raymondwzeng** [comment]
> Looks good to me. Let's create an issue to make unit tests for the client POST request so that we can verify that it works without having to start the server.

Off the top of my head, there's no good way that I can think of to do this. Technically speaking the server is only running when we actually, well, run it on our machines, so the POST request would simply fail if it was sent on the client without the server being active.

**Review by garrettgeesink — APPROVED** [review]
looks good

**Pull request merged**
